__title__ = "fast-ulid"
__description__ = "Easy to use ULID generator"
__url__ = "https://github.com/nagataaaas/fast-ulid"
__version_info__ = ("0", "1", "0")
__version__ = ".".join(__version_info__)
__author__ = "Yamato Nagata"
__author_email__ = "chickenwingswillfly@gmail.com"
__maintainer__ = "Yamato Nagata"
__license__ = "MIT"
__copyright__ = "(c) 2022 by Yamato Nagata"
